apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: login
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: login
    spec:
      containers:
        - image: docker.io/anastasiabrinati/src-login
          name: login
          ports:
            - containerPort: 50051
          resources: {}
          volumeMounts:
            - mountPath: /src
              name: login-claim0
      restartPolicy: Always
      volumes:
        - name: login-claim0
          persistentVolumeClaim:
            claimName: login-claim0
status: {}
