apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: search-forecast
  name: search-forecast
spec:
  ports:
    - name: "50054"
      port: 50054
      targetPort: 50054
  selector:
    io.kompose.service: search-forecast
status:
  loadBalancer: {}
