apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: search-past
  name: search-past
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search-past
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: search-past
    spec:
      containers:
        - image: docker.io/anastasiabrinati/src-search-past:latest
          name: search-past
          ports:
            - containerPort: 50052
          resources: {}
      restartPolicy: Always
status: {}
