apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: search-forecast
  name: search-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search-forecast
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: search-forecast
    spec:
      containers:
        - image: docker.io/anastasiabrinati/src-search-forecast:latest
          name: search-forecast
          ports:
            - containerPort: 50054
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Always
status: {}
