apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: user
    spec:
      containers:
        - image: docker.io/anastasiabrinati/src-user:latest
          name: user
          ports:
            - containerPort: 50051
          resources: {}
          volumeMounts:
            - mountPath: /src
              name: user-claim0
      restartPolicy: Always
      volumes:
        - name: user-claim0
          persistentVolumeClaim:
            claimName: user-claim0
status: {}
