# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/login.proto\x12\x05proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1d\n\nLoginReply\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\x32=\n\x08Loginner\x12\x31\n\x05Login\x12\x13.proto.LoginRequest\x1a\x11.proto.LoginReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.login_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=28
  _globals['_LOGINREQUEST']._serialized_end=78
  _globals['_LOGINREPLY']._serialized_start=80
  _globals['_LOGINREPLY']._serialized_end=109
  _globals['_LOGINNER']._serialized_start=111
  _globals['_LOGINNER']._serialized_end=172
# @@protoc_insertion_point(module_scope)
