# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import user_pb2 as proto_dot_user__pb2


class UsererStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/proto.Userer/Login',
                request_serializer=proto_dot_user__pb2.LoginRequest.SerializeToString,
                response_deserializer=proto_dot_user__pb2.LoginReply.FromString,
                )
        self.AddToFav = channel.unary_unary(
                '/proto.Userer/AddToFav',
                request_serializer=proto_dot_user__pb2.AddToFavRequest.SerializeToString,
                response_deserializer=proto_dot_user__pb2.AddToFavReply.FromString,
                )


class UsererServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToFav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsererServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=proto_dot_user__pb2.LoginRequest.FromString,
                    response_serializer=proto_dot_user__pb2.LoginReply.SerializeToString,
            ),
            'AddToFav': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToFav,
                    request_deserializer=proto_dot_user__pb2.AddToFavRequest.FromString,
                    response_serializer=proto_dot_user__pb2.AddToFavReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Userer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Userer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Userer/Login',
            proto_dot_user__pb2.LoginRequest.SerializeToString,
            proto_dot_user__pb2.LoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToFav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Userer/AddToFav',
            proto_dot_user__pb2.AddToFavRequest.SerializeToString,
            proto_dot_user__pb2.AddToFavReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
