# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import discovery_pb2 as proto_dot_discovery__pb2


class DiscoveryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.discoveryLogin = channel.unary_unary(
                '/proto.DiscoveryService/discoveryLogin',
                request_serializer=proto_dot_discovery__pb2.DiscoveryLoginRequest.SerializeToString,
                response_deserializer=proto_dot_discovery__pb2.DiscoveryLoginReply.FromString,
                )
        self.put = channel.unary_unary(
                '/proto.DiscoveryService/put',
                request_serializer=proto_dot_discovery__pb2.PutRequest.SerializeToString,
                response_deserializer=proto_dot_discovery__pb2.PutReply.FromString,
                )


class DiscoveryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def discoveryLogin(self, request, context):
        """
        Consente di comunicare con il
        microservizio passato come parametro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def put(self, request, context):
        """
        Consente di registrare la porta relativa
        al microservizio passato come parametro.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'discoveryLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.discoveryLogin,
                    request_deserializer=proto_dot_discovery__pb2.DiscoveryLoginRequest.FromString,
                    response_serializer=proto_dot_discovery__pb2.DiscoveryLoginReply.SerializeToString,
            ),
            'put': grpc.unary_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=proto_dot_discovery__pb2.PutRequest.FromString,
                    response_serializer=proto_dot_discovery__pb2.PutReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def discoveryLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.DiscoveryService/discoveryLogin',
            proto_dot_discovery__pb2.DiscoveryLoginRequest.SerializeToString,
            proto_dot_discovery__pb2.DiscoveryLoginReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.DiscoveryService/put',
            proto_dot_discovery__pb2.PutRequest.SerializeToString,
            proto_dot_discovery__pb2.PutReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
