# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/searchpast.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/searchpast.proto\x12\x05proto\"!\n\x11SearchPastRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"\xc4\x01\n\x0fSearchPastReply\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x17\n\x0fmax_temperature\x18\x03 \x01(\x02\x12\x17\n\x0fmin_temperature\x18\x04 \x01(\x02\x12\x17\n\x0f\x61vg_temperature\x18\x05 \x01(\x02\x12\x14\n\x0cmax_humidity\x18\x06 \x01(\x02\x12\x14\n\x0cmin_humidity\x18\x07 \x01(\x02\x12\x14\n\x0c\x61vg_humidity\x18\x08 \x01(\x02\x12\x16\n\x0e\x61vg_cloudcover\x18\t \x01(\x02\x32L\n\x0cSearcherPast\x12<\n\x06Search\x12\x18.proto.SearchPastRequest\x1a\x16.proto.SearchPastReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.searchpast_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SEARCHPASTREQUEST']._serialized_start=33
  _globals['_SEARCHPASTREQUEST']._serialized_end=66
  _globals['_SEARCHPASTREPLY']._serialized_start=69
  _globals['_SEARCHPASTREPLY']._serialized_end=265
  _globals['_SEARCHERPAST']._serialized_start=267
  _globals['_SEARCHERPAST']._serialized_end=343
# @@protoc_insertion_point(module_scope)
