- hosts: localhost
  pre_tasks:
  - name: Update(or clone) the Git repository
    git:
      repo: https://github.com/AnastasiaBrinati/SDCC_project_22-23.git
      dest: /home/ubuntu/CloudyDays
      update: yes
  - name: sudo apt update
    command: sudo apt-get update -y
  - name: sudo apt upgrade
    command: sudo apt-get upgrade -y
  - name: certificates
    command: sudo apt install apt-transport-https ca-certificates curl software-properties-common
  - name: add the GPG key for the official Docker repository to your system
    command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: add Docker repo to APT sources
    command: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
  - name: installing from the Docker repo
    command: apt-cache policy docker-ce
  - name: Install docker-ce
    command: sudo apt install docker-ce
  - name: Install Minikube dependencies
    command: sudo apt install -y curl wget apt-transport-https
  - name: Download Minikube Binary
    command: curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - name: Install Minikube
    command: sudo install minikube-linux-amd64 /usr/local/bin/minikube
  - name: Install Kubectl utility
    command: curl -LO https://dl.k8s.io/release/v1.28.3/bin/linux/amd64/kubectl
  - name: chmod kubectl
    command: sudo chmod +x ./kubectl
  - name: mv kubectl
    command: sudo mv ./kubectl /usr/local/bin/
  - name: Minikube Start
    command: minikube start --vm-driver docker
