- hosts: localhost
  pre_tasks:
  - name: Update(or clone) the Git repository
    git:
      repo: https://github.com/AnastasiaBrinati/SDCC_project_22-23.git
      dest: /home/ubuntu/CloudyDays
      update: yes
  - name: check the status of minikube.
      command: minikube status
      register: minikube_status
      changed_when: false
      ignore_errors: true

  tasks:
  - name: start minikube if it's not running.
      command: minikube start --vm = true
      when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

  post_tasks:
    - name: exposing Cloudy Days on the host via Minikube.
      command: minikube tunnel
      changed_when: false
