- hosts: localhost
  tasks:
  - name: Ensure that git is installed
    apt:
      name: git
      state: present

  - name: Clone the Git repository
    git:
      repo: https://github.com/AnastasiaBrinati/SDCC_project_22-23.git
      dest: /home/ubuntu/
      clone: yes
