- hosts: localhost
  pre_tasks:
  - name: Update(or clone) the Git repository
    git:
      repo: https://github.com/AnastasiaBrinati/SDCC_project_22-23.git
      dest: /home/ubuntu/CloudyDays
      update: yes
  - name: sudo install minikube
    sudo apt:
      deb: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb"
      state: present
