version: "3.8"

services:

# essentials for service discovery

  api-gateway:
    build: ./api-gateway
    user: root
    ports:
      - "50050:50050"

# actual microservices

  frontend:
    build: ./frontend
    user: root
    ports:
      - 5000:5000

  login:
    build: ./login
    user: root
    ports:
      - 50051:50051
    volumes:
      - ./:/src
    environment:
      - ./.env

  search-past:
    build: ./search-past
    user: root
    ports:
      - 50052:50052
    depends_on:
      - cache

  search-now:
    build: ./search-now
    user: root
    ports:
      - 50053:50053
    depends_on:
      - cache

  search-forecast:
    build: ./search-forecast
    user: root
    ports:
      - 50054:50054
    depends_on:
      - cache

# utilities
  
  mysql:
    build: ./db-login
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: users
    ports:
      - 3306:3306

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

volumes:
  todo-mysql-data:
  cache:
    driver: local
