version: "3.8"

services:

# essentials for service discovery

  api-gateway:
    build: ./api-gateway
    user: root
    ports:
      - "50050:50050"

# actual microservices

  frontend:
    build: ./frontend
    user: root
    ports:
      - 5000:5000

  login:
    build: ./login
    user: root
    ports:
      - 50051:50051
    volumes:
      - ./:/src
    environment:
      - ./.env

  
  search:
    build: ./search
    user: root
    ports:
      - 50052:50052

# utilities
  
  mysql:
    build: ./db-login
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: users
    ports:
      - 3306:3306

volumes:
  todo-mysql-data: