version: "3.8"

services:

# actual microservices

  frontend:
    build: ./frontend
    user: root
    ports:
      - 5000:5000

  login:
    build: ./login
    user: 50051:50051
  
# essentials for service discovery
