apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: src-login
  name: src-login
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: src-login
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: src-login
    spec:
      containers:
        - image: src-login
          name: src-login
          ports:
            - containerPort: 50051
          resources: {}
      restartPolicy: Always
status: {}
