apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: src-search
  name: src-search
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: src-search
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: src-search
    spec:
      containers:
        - image: src-search
          name: src-search
          ports:
            - containerPort: 50052
          resources: {}
      restartPolicy: Always
status: {}
